# Generated by Django 2.0.7 on 2018-07-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=32)),
                ('visited', models.BooleanField(default=False)),
                ('upload', models.FileField(upload_to='songs/')),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapchat.Snap')),
            ],
        ),
    ]
