# Generated by Django 2.0.7 on 2018-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='token',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
