# Generated by Django 2.0.7 on 2018-07-27 19:18

from django.db import migrations, models
import snapchat.models
import snapchat.validators


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload',
            field=models.FileField(upload_to=snapchat.models.Song.get_random_song_path, validators=[snapchat.validators.FileValidator(content_types=('application/mp3', 'application/x-mp3', 'audio/aac', 'audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/x-wav', 'audio/ogg', 'audio/webm', 'audio/3gpp', 'audio/3gpp2', 'audio/basic', 'auido/L24', 'audio/mid', 'audio/mp4', 'audio/x-aiff', 'audio/x-mpegurl', 'audio/vnd.rn-realaudio', 'audio/vorbis', 'audio/vnd.wav'), max_size=20971520)]),
        ),
    ]
