# Generated by Django 2.0.7 on 2018-07-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0004_auto_20180720_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
