# Generated by Django 2.0.7 on 2018-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0004_remove_song_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_format',
        ),
        migrations.AlterField(
            model_name='song',
            name='upload',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
