# Generated by Django 2.0.7 on 2018-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0005_auto_20180721_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snap',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='snap',
            name='finished_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snap',
            name='token',
            field=models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='token',
            field=models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
