# Generated by Django 2.0.7 on 2018-07-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0005_auto_20180712_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='token',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
