# Generated by Django 2.0.7 on 2018-07-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('visited', models.BooleanField(default=False)),
                ('file_format', models.CharField(max_length=4)),
                ('upload', models.FileField(upload_to='songs/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapchat.Profile')),
            ],
        ),
    ]
