# Generated by Django 2.0.7 on 2018-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0002_auto_20180712_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='filename',
            field=models.CharField(default='filename', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='upload',
            field=models.FileField(upload_to='media/songs/'),
        ),
    ]
