# Generated by Django 2.0.7 on 2018-07-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0003_auto_20180712_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='filename',
        ),
    ]
